### ISSUE TITLE
Exception in logout

### ISSUE THREAD

**Issue by michaelarnauts** [costastf/locationsharinglib#1]
The fetching-code seems to work fine, since I get a result. However, in the destroy, the code is logging me out, and that is giving an exception.

```
Exception ignored in: <bound method Service.__del__ of <locationsharinglib.locationsharinglib.Service object at 0x7f8cf3e77588>>
Traceback (most recent call last):
  File "/mnt/c/Users/micha/Development/locationsharinglib/locationsharinglib/locationsharinglib.py", line 210, in __del__
  File "/mnt/c/Users/micha/Development/locationsharinglib/locationsharinglib/locationsharinglib.py", line 206, in _logout
  File "/usr/local/lib/python3.5/dist-packages/requests-2.18.4-py3.5.egg/requests/sessions.py", line 521, in get
  File "/usr/local/lib/python3.5/dist-packages/requests-2.18.4-py3.5.egg/requests/sessions.py", line 494, in request
  File "/usr/local/lib/python3.5/dist-packages/requests-2.18.4-py3.5.egg/requests/sessions.py", line 419, in prepare_request
  File "/usr/local/lib/python3.5/dist-packages/requests-2.18.4-py3.5.egg/requests/cookies.py", line 537, in merge_cookies
  File "/usr/local/lib/python3.5/dist-packages/requests-2.18.4-py3.5.egg/requests/cookies.py", line 353, in update
  File "/usr/lib/python3.5/copy.py", line 97, in copy
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 887, in _find_spec
TypeError: 'NoneType' object is not iterable
```

**Comment by michaelarnauts** [comment]
It seems `https://accounts.google.com/Logout/` isn't a valid url to logout. It gives a 404 to me.

Edit: the url chould be without the trailing slash:
```python
        url = '{login_url}/Logout'.format(login_url=self._login_url)
```

But that unfortunately doesn't fix the issue.

**Comment by costastf** [comment]
Should have been fixed with version 0.1.3 I just pushed. Thanks!

**Comment by costastf** [comment]
It was the trailing slash that was breaking it. Currently works without it. I did not see your edit until I had fixed it already. It seems to work now without the trailing slash, so if you have any issues please reopen this.

**Comment by michaelarnauts** [comment]
There is no way to reopen an issue in Github if you have no permissions in the repository :) 
I still have the issue, can you reopen?

I'm not sure what the issue is, since it's somewhere in the middle of the `requests` code.

**Comment by costastf** [comment]
There are versions 0.1.3 with the hardcoded url and without a redirect and version 0.1.4 with the initial url and no slash in the end. Could you please try out both and provide feedback?

**Comment by michaelarnauts** [comment]
I'm using this repository and installed it with `python3 setup.py develop`.

It seems the `_logout()` method works fine if I call it directly, but if automatically invoked from the `__del()` method, it doesn't work anymore. I guess because the `Session` object is already destroyed?

**Comment by michaelarnauts** [comment]
Maybe you are calling the logout yourself in your tests?

**Comment by costastf** [comment]
Yes i do. Hm.. thats kinda tricky. I do not get why the session would be destroyed already since it has dependent references.

**Comment by costastf** [comment]
Looking at your stacktrace, the session is not deleted since it calls internal methods to update cookies. But somewhere there something is trying to iterate something already deleted.

**Comment by costastf** [comment]
Apparently I closed the issue by mistake :)

**Comment by costastf** [comment]
On python 2.7.14 with requests 2.18.4 I do not get a stack trace when doing "del service"

**Comment by michaelarnauts** [comment]
I'm testing with 3.6...

This seems related: https://joekuan.wordpress.com/2015/06/30/python-3-__del__-method-and-imported-modules/

**Comment by michaelarnauts** [comment]
Actually, is logging out really required? A web page won't logout when you close the tab, right?

**Comment by costastf** [comment]
Well, the problem is that the session is sticky and if you get a lot of reboots you will get a lot of open sessions with google, and that might start bells ringing with all the systems Google has and it might lead to a lot of attention to the account monitoring the shared location.

**Comment by costastf** [comment]
Maybe if we wrap the _logout with an exception handler that would just mute any issue? Would you like to give that a try? It seems that there is not much we can do except silence the issue if and when it occurs.

**Comment by michaelarnauts** [comment]
Hmm, I see your point of logging out, but I guess those bells are also ringing when the same amount of logins and logouts are happening, no?

I guess wrapping in an exception handler is also fine, but you could also leave invokation of logging out to the implementation of this library. They can just call the  `_logout()` call themselves.

**Comment by michaelarnauts** [comment]
Maybe a better solution is to dump the cookies to disk somewhere so they an be reused in a next process? That way, it would seem like one session to google, more like a browser would do.

**Comment by costastf** [comment]
That could be an idea. I will implement it at some point during the coming week and make the log out user manageable.

**Comment by costastf** [comment]
Do you want to give version 0.2.0 a try and tell me how it feels? I have exposed the logout as a public method to be used explicitly, added an export_session(path) method to pickle the cookies and the service gets an extra argument of cookies_file that can load the cookies and test their validity.

**Comment by costastf** [comment]
I trust that this can be closed since the logout is not called by the garbage collector any more.
